In [1]:
# pip install numpy
# conda install numpy

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5]) # rank 1 array (vector)
print(a)

[1 2 3 4 5]


In [4]:
print(type(a))

<class 'numpy.ndarray'>


In [5]:
print(a.shape)

(5,)


In [6]:
print(a[0], a[3])

1 4


In [7]:
a[0] = 55
print(a)

[55  2  3  4  5]


In [8]:
b = np.array([
    [1,2,3],
    [4,5,6]
]) # rank 2 array
print(b.shape)

(2, 3)


In [9]:
print(b[1,2])

6


In [10]:
a = np.zeros((3,5))
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
b = np.ones((2,3))
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]


In [13]:
c = np.full((5,5), 7.0)
print(c)

[[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]]


In [14]:
d = np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [15]:
e = np.random.random((3,4))
print(e)

[[0.04703616 0.35534775 0.46739226 0.0450786 ]
 [0.44375342 0.36219267 0.23422825 0.80405845]
 [0.39264066 0.29509701 0.35271103 0.45722444]]


In [18]:
e = np.random.randint(5, size=(3,5))
print(e)

[[4 2 3 3 3]
 [1 2 3 2 0]
 [2 0 4 1 3]]


In [19]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
b = a[:2, 1:3] # create a view
print(b)

[[2 3]
 [6 7]]


In [20]:
print(a[0,1])

2


In [21]:
b[0,0] = 77
print(b)

[[77  3]
 [ 6  7]]


In [22]:
print(a[0,1])

77


In [23]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
r1 = a[1, :]
print(r1)

[5 6 7 8]
