In [1]:
import tensorflow as tf
print(tf.__version__)

2.3.0


In [3]:
a = tf.Variable('This is a string test', tf.string)
print(a)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'This is a string test'>


In [5]:
b = tf.Variable(123, tf.int32)
print(b)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=123>


In [6]:
c = tf.Variable(123.345, tf.float32)
print(c)

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=123.345>


In [7]:
a = tf.Variable(['test'], tf.string)
print(a)

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'test'], dtype=object)>


In [8]:
b = tf.Variable([
    ['tensorflow', 'pytorch'],
    ['bad', 'good']
], tf.string)

print(b)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'tensorflow', b'pytorch'],
       [b'bad', b'good']], dtype=object)>


In [9]:
print(b.shape)

(2, 2)


In [10]:
t1 = tf.zeros(5)
print(t1)

tf.Tensor([0. 0. 0. 0. 0.], shape=(5,), dtype=float32)


In [12]:
t2 = tf.ones(5)
print(t2)

tf.Tensor([1. 1. 1. 1. 1.], shape=(5,), dtype=float32)


In [13]:
t3 = tf.ones([2,3])
print(t3)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [14]:
t4 = tf.ones([1,2,3])
print(t4)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [15]:
t5 = tf.ones([2,2,3])
print(t5)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 2, 3), dtype=float32)


In [20]:
t6 = tf.reshape(t4, [2,3,1])
print(t6)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [21]:
t7 = tf.reshape(t6, [3, 2])
print(t7)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [22]:
t8 = tf.reshape(t6, [3, -1])
print(t8)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


In [23]:
l1 = [
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20]
]
print(type(l1))

<class 'list'>


In [24]:
t9 = tf.Variable(l1, dtype=tf.float32)
print(t9)

<tf.Variable 'Variable:0' shape=(4, 5) dtype=float32, numpy=
array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.]], dtype=float32)>


In [25]:
print(t9[0,2])

tf.Tensor(3.0, shape=(), dtype=float32)


In [26]:
print(t9[0])

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)


In [27]:
print(t9[:,0])

tf.Tensor([ 1.  6. 11. 16.], shape=(4,), dtype=float32)


In [28]:
print(t9[1::2])

tf.Tensor(
[[ 6.  7.  8.  9. 10.]
 [16. 17. 18. 19. 20.]], shape=(2, 5), dtype=float32)


In [29]:
print(t9[1:3, 0])

tf.Tensor([ 6. 11.], shape=(2,), dtype=float32)
